version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-broker
    ports:
      # Port for our Go/Python code to connect to
      - "5672:5672"
      # Port for the web-based Management UI
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest